# Site settings
title: 逐流的喫茶方舟
email: danielshen@yahoo.com
description: > # this means to ignore newlines until "baseurl:"
  百鸟可知悲哀.
baseurl: "http://zhuliuabi.com" # the subpath of your site, e.g. /newpath-for-emping
url: "http://zhuliuabi.com" # the base hostname & protocol for your site
twitter_username: hemmyshen
github_username:  ZhuliuAiagle
GoogleAnalytics: UA-xxxxxx-x

twitter:
  username: hemmyshen
facebook:
  app_id: 1234567
  publisher: 1234567

sass:
    style: compressed

# Build settings
markdown: kramdown
kramdown:
  parse_block_html: true

gems:
  - jekyll-redirect-from
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-feed
  - jemoji

defaults:
    - {scope: {type: posts}, values: {layout: post, permalink: '/blog/:title'}}

include:
  - _pages

exclude:
  - CNAME
  - README.md
  - Gemfile
  - Gemfile.lock

paginate: 12
paginate_path: '/blog/:num'
